server:
  port: 8080
spring:
  sql:
    init:
      mode: never
  mustache:
    check-template-location: false
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
  jpa:
    defer-datasource-initialization: false
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    open-in-view: true
    hibernate:
      ddl-auto: none # create none
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  datasource:
    url: jdbc:sqlite:./yotsuba.db
    driver-class-name: org.sqlite.JDBC
    hikari:
      connectionInitSql: PRAGMA foreign_keys = ON;
  flyway:
    baseline-on-migrate: true
    enabled: true
logging:
  level:
    org:
      atmosphere: warn
      hibernate:
        orm:
          jdbc:
            bind: trace
vaadin:
  launch-browser: 'true'
  allowed-packages: com.vaadin,org.vaadin,io.github.dutianze
  pnpm:
    enable: 'true'
  excludeUrls: /swagger-ui/**


